# FROM ubuntu
# ENTRYPOINT: "sleep"
# CMD: "5" <-- is going to be default value, but it's overwrited.
# ex) docker run ubuntu-sleeper sleep 10 <- commnad at startup 
#     docker run ubuntu-sleeper 10 <- entrypoint 
apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-sleeper-pod 
spec:
    containers:
        - name: ubuntu-sleeper 
          image: ubuntu-sleeper 
          command: # or args - --color
            - "sleep"
            - "2000"