apiVersion: v1
kind: Pod
metadata:
    name: simple-webapp
    labels:
        name: simple-webapp
spec:
    containers:
        - name: simple-webapp 
          image: simple-webapp 
          ports: 
            - containerPort: 8080
          envFrom: # same concepts as config map
            - secretRef: # only different this
                name: app-secret # secret name