apiVersion: v1
kind: Pod
metadata:
    name: simple-webapp
    labels:
        name: simple-webapp 
spec:
    containers:
        - name: simple-webapp 
          iamge: simple-webapp 
          ports:
            - containerPort: 8080
        - name: log-agent
          iamge: log-agent 