# stores secret value such as db name passwd, etc
# 1. Create secrte: kubectl create secret generic (imperative) 
#                   kubectl create -f ' '  (decrative) 
# env, single env, and volume 
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
data:
    DB_Host: mysql
    DB_User: .... 
    DB_Password: .... # tries to use hashed value or encoded value

