apiVersion: v1
kind: Service
metadata: 
    name: back-end
spec:
    type: ClusterIP # other layer communicates with each layer's clusterIP 
    ports:
        - tartgetPort: 80
          port: 80
    selector:
        app: myapp
        type: back-end 