apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
        - name: data-processor
          image: data-processor
    affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: size
                          operator: In # NotIn 
                          values:
                            - Large # With 'NotIn' -> Small or Medium
# More information: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
                    