apiVersion: v1
kind: Service
metadata:
    name: myapp-service 
spec:
    type: NodePort # ClusterIP, LoadBalancer
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30008 # Range 30000 - 32767 
    selector: # uses provided list of labels
        app: myapp
        type: front-end
