apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: cluster-administrator-binding 
subjects:
    - kind: User
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io 
    roleRef:
        kind: ClusterRole 
        name: Cluster-administrator
        apiGroup: rbac.authorization.k8s.io 