apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    name: kube-apiserver
    namespace: kube-system
spec:
    containers:
        - command:
            - kube-apiserver
            - --authorization-mode=Node,RBAC
            - --advertise-address=172.17.0.107
            - --allow-privileged=true
            - --enable-admission-plugins=NodeRestriction
            - --enable-bootstrap-token-auth=true
            - --basic-auth-file=/tmp/users/user-details.csv # modify basic-auth file at kube-apiserver
            image: k8s.qcr.io/kube-apiserver-amd64:v1.11.3
            name: kube-apiserver 