apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadta:
    name: db-policy
spec:
    podSelector:
        metchLabels:
            role: db 
        policyTypes:
            - Ingress
        ingress:
            - from:
                - podSelector:
                    matchLabels:
                        name: api-pod
                ports:
                    - protocol: TCP 
                      port: 3306 

                      