apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: developer
rules:
    - apiGroups: [""]
      resources: [""]
      verbs: [""] 
      # or we can put multiple rule
      resourceNames: [""] # if we want to sepcify several pods among on same namespace. 
