apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-voll
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    awsElasticBlockStore:
        volumeID:
        fsType: 